/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criptografia;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author tonoh
 */
public class Main extends javax.swing.JFrame {

    private JFrame frame;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        Area2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Long2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area1 = new javax.swing.JTextArea();
        Selecc = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        Activado = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        input = new javax.swing.JLabel();
        input1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        Long3 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Long2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Long2.setForeground(new java.awt.Color(240, 240, 240));
        Long2.setText("Longitud: ");
        jPanel1.add(Long2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, 140, 60));

        Area2.setColumns(20);
        Area2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Area2.setRows(5);
        jScrollPane1.setViewportView(Area2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 450, 400));

        Area1.setColumns(20);
        Area1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Area1.setRows(5);
        jScrollPane2.setViewportView(Area1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 450, 400));

        Selecc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Selecc.setText("Encriptar");
        Selecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccActionPerformed(evt);
            }
        });
        jPanel1.add(Selecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 140, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("EJECUTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 120, 50));

        Activado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Activado.setForeground(new java.awt.Color(240, 240, 240));
        Activado.setText("Modo : ");
        jPanel1.add(Activado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo2.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 150));

        status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 51, 51));
        status.setText("Desencriptar");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stop_exit_close_1062.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 60, 60));

        input.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        input.setForeground(new java.awt.Color(255, 51, 51));
        input.setText("Output");
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 50, 30));

        input1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        input1.setForeground(new java.awt.Color(0, 255, 0));
        input1.setText("Input");
        jPanel1.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 30));

        Titulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(240, 240, 240));
        Titulo1.setText("Criptografia");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 290, 60));

        L2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L2.setForeground(new java.awt.Color(240, 240, 240));
        L2.setText("0");
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 90, 60));

        Long3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Long3.setForeground(new java.awt.Color(240, 240, 240));
        Long3.setText("Longitud: ");
        jPanel1.add(Long3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 140, 60));

        L1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L1.setForeground(new java.awt.Color(240, 240, 240));
        L1.setText("0");
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 100, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccActionPerformed
        if (Selecc.isSelected()) {
            Selecc.setText("Desencriptar");
            status.setText("Encriptacion");
            status.setForeground(Color.GREEN);
        } else {
            Selecc.setText("Encriptar");
            status.setText("Desencriptacion");
            status.setForeground(Color.RED);
        }
    }//GEN-LAST:event_SeleccActionPerformed

    public void mostrarVentanaCarga(JFrame parentFrame, Runnable despuesDeCarga) {
        JDialog dialogo = new JDialog(parentFrame, "Procesando...", true);
        dialogo.setSize(300, 120);
        dialogo.setLayout(new BorderLayout());
        dialogo.setLocationRelativeTo(parentFrame);

        JLabel mensajeLabel = new JLabel("Iniciando...", SwingConstants.CENTER);
        JProgressBar barra = new JProgressBar();
        barra.setIndeterminate(true); // Carga infinita visual

        dialogo.add(mensajeLabel, BorderLayout.CENTER);
        dialogo.add(barra, BorderLayout.SOUTH);

        // Mostrar el diálogo en un hilo nuevo para no congelar la interfaz
        new Thread(() -> {
            String[] mensajes = {
                "Encriptando...",
                "Descifrando...",
                "Hackeando NASA...",
                "Destruyendo evidencias...",
                "Cargando virus... 😈",
                "Listo para lanzar 🚀"
            };

            for (String mensaje : mensajes) {
                mensajeLabel.setText(mensaje);
                try {
                    Thread.sleep(700); // Espera entre cada mensaje
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }

            dialogo.dispose(); // Cierra el popup
            SwingUtilities.invokeLater(despuesDeCarga); // Ejecuta lo siguiente
        }).start();

        dialogo.setVisible(true);
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Area1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(jPanel1, "Escribe un mensaje", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            Clave clv = new Clave();
            String clave = clv.getClave();

            mostrarVentanaCarga(frame, () -> {

                String txtT, txtN;
                String resultado;
                String txt = Area1.getText();
                int longitud1 = txt.length();
                String lon1 = longitud1 + "";
                if (Selecc.isSelected()) {
                    txtT = Transposicion.transponer(txt);
                    txtT = Transposicion.numeros_vocales(txtT);
                    resultado = Clave.aplicarClave(txtT, clave);
                } else {
                    String txt2 = Area1.getText();
                    txtN = Clave.quitarClave(txt2, clave);
                    txtN = Transposicion.numeros_vocales(txtN);
                    resultado = Transposicion.transponer(txtN);

                }
                Area2.setText(resultado);
                String txt2 = Area2.getText();
                int longitud2 = txt2.length();
                String lon2 = longitud2 + "";
                L1.setText(lon1);
                L2.setText(lon2);
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Activado;
    private javax.swing.JTextArea Area1;
    private javax.swing.JTextArea Area2;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Long2;
    private javax.swing.JLabel Long3;
    private javax.swing.JToggleButton Selecc;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel input;
    private javax.swing.JLabel input1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}